# Site settings
title: Vydří stezky
description: >-
  Představení vydry říční – naši největší šelmu vod – a základní
  informace a novinky o tzv. Vydřích stezkách.
baseurl: ""
url: https://www.vydristezky.cz
author: alka-wildlife

# Integrations and machine-readable metadata
facebook:
  app_id: 145375228868712
  publisher: 269120446533000
  admins: 1133305906
logo: /uploads/vyd___stezka_logo_-_pr_hledn_.png
social:
  name: ALKA Wildlife, o.p.s.
  links:
    - https://www.facebook.com/AlkaWildlife
webmaster_verifications:
  google: o27dsTgYww0bzXVmTZ_CgadoY8QtzpDMgo-bVSgH3OM
lang: cs-CZ
google_analytics: UA-57533252-5

# Collection settings
collections:
  md_pages:
    output: true
  galleries: {}
  posts:
    permalink: /:categories/:title
  showcases: {}
  filterable_tags: {}

# Build settings
markdown: kramdown
kramdown:
  smart_quotes: 0x0201A,0x02018,0x0201E,0x0201C
  header_offset: 3
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Exclude from processing.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - Rakefile
  - rakelib
  - bin

# Prevent from clobbering.
# Netlify CMS and Netlify Identity Widget assets are created before
# Jekyll build via Rake build task.
keep_files:
  - assets/javascripts/cms.js
  - assets/javascripts/cms.js.map
  - assets/stylesheets/cms.css
  - assets/javascripts/netlify-identity-widget.js
  - assets/javascripts/netlify-identity-widget.js.map
