# Site settings
title: Vydří stezky
description: >-
  Představení vydry říční – naši největší šelmu vod – a základní
  informace a novinky o tzv. Vydřích stezkách.
baseurl: ""
url: https://www.vydristezky.cz

# Integrations and machine-readable metadata
facebook:
  app_id: 145375228868712
  publisher: 269120446533000
  admins: 1133305906
logo:
  "/uploads/vyd___stezka_logo_-_pr_hledn_.png"
social:
  name: ALKA Wildlife, o.p.s.
  links:
    - https://www.facebook.com/AlkaWildlife
webmaster_verifications:
  google: o27dsTgYww0bzXVmTZ_CgadoY8QtzpDMgo-bVSgH3OM
lang: cs-CZ
google_analytics: UA-57533252-5

# Collection settings
collections:
  galleries: {}
  posts:
    output: true
    permalink: "/news/:title"
  showcases: {}
  filterable_tags: {}
  photos: {}

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - node_modules
  - Rakefile
  - rakelib
  - bin

# Prevent from clobbering.
# Netlify CMS and Netlify Identity Widget assets are created before Jekyll
# build via make utility.
keep_files:
  - assets/cms.js
  - assets/cms.js.map
  - assets/cms.css
  - assets/netlify-identity-widget.js
  - assets/netlify-identity-widget.js.map
