backend:
  name: git-gateway
  branch: master

media_folder: uploads

collections:
- name: md_pages
  label: Pages
  label_singular: Page
  description: >-
    Simple pages with single- or two-columns layout. The pages form a
    hierarchy with created from their addresses. The top-most page in
    the hierarchy is home page with address “/”. Its children are News
    (“/news”), Gallery (“/gallery”) and Search (“/search”). Previously
    named pages are special – do not create page with their addresses
    or their children yourself. Anythis else is up to you… You can for
    example create About Us page (“/about”) and then its child page
    Our Team (“/about/team”). This hierarchy is used to generate
    navigation menu, sibling pages (in the right column) and child
    pages (under page content).
  folder: _md_pages
  create: true
  fields:
  - name: title
    label: Title
    widget: string
  - name: permalink
    label: Address (creates hierarchy—e.g., “/about/team” is a child of “/about” which is a child of “/”)
    widget: string
  - name: image
    label: Image (610 × 358 px)
    widget: image
    required: false
  - name: long_title
    label: Long title (heading right above content; defaults to plain title)
    widget: string
    required: false
  - name: subtitle
    label: Subtitle (optional small heading under long title)
    widget: string
    required: false
  - name: body
    label: Body
    widget: markdown
  - name: published
    label: Published (publicly available under address)
    widget: boolean
  - name: listed
    label: Show in the navigation menu
    widget: boolean
  - name: position
    label: Position among siblings in listings
    widget: number
    valueType: int
  - name: layout
    label: Layout
    widget: string
    #TODO
    # widget: relation
    # collection: layouts
    # valueField: ref
    # searchFields:
    # - title
  - name: aside_title
    label: Heading for aside
    widget: string
    required: false
  - name: aside_links
    label: Content for aside above sibling pages listing
    widget: markdown
    required: false
  meta:
  - name: date
    label: Created at
    widget: date
    format: YYYY-MM-DD HH:mm:ss ZZ

- name: galleries
  label: Galleries
  label_singular: Gallery
  description: >-
    Photo galleries linked to any content via its address. Gallery
    photos are displayed under the content.
  folder: _galleries
  create: true
  fields:
  - name: page
    label: Page address (copy and paste from web browser address bar, and remove https:// and domain)
    widget: string
  - name: position
    label: Position
    widget: number
    valueType: int
  meta:
  - name: date
    label: Created at
    widget: date
    format: YYYY-MM-DD HH:mm:ss ZZ

- name: posts
  label: News
  folder: _posts
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  create: true
  fields:
  - name: title
    label: Title
    widget: string
  - name: image
    label: Image
    widget: image
  - name: body
    label: Content
    widget: markdown
  - name: published
    label: Published
    widget: boolean
  - name: date
    label: Published at
    widget: date
    format: YYYY-MM-DD

- name: showcases
  label: Showcases
  label_singular: Showcase
  description: Big photos that are displayed on the homepage.
  folder: _showcases
  create: true
  fields:
  - name: title
    label: Title
    widget: string
  - name: image
    label: Image
    widget: image
  - name: position
    label: Position
    widget: number
    valueType: int
  meta:
  - name: date
    label: Created at
    widget: date
    format: YYYY-MM-DD HH:mm:ss ZZ

- name: filterable_tags
  label: Categories
  label_singular: Category
  description: >-
    Categorization and filtering of photos. Arbitrary categories can
    be added to photos (i.e., photo categories don’t have to defined
    here). But if you want a category to appear as a filter option on
    the global photo gallery page, you have to define it here with
    exactly same name as you use in photos.
  folder: _filterable_tags
  create: true
  fields:
  - name: name
    label: Name
    widget: string
  - name: position
    label: Position
    widget: number
    valueType: int
  meta:
  - name: date
    label: Created at
    widget: date
    format: YYYY-MM-DD HH:mm:ss ZZ

- name: photos
  label: Photos
  label_singular: Photo
  description: >-
    Photos in linked to galleries. All photos are displayed on global
    photo gallery.
  folder: _photos
  create: true
  fields:
  - name: title
    label: Title
    widget: string
  - name: image
    label: Image
    widget: image
  - name: body
    label: Description
    widget: markdown
    required: false
  - name: author
    label: Author
    widget: string
    required: false
  - name: tags
    label: Categories
    widget: list
    required: false
  - name: gallery
    label: Gallery
    widget: relation
    collection: galleries
    searchFields:
    - page
    valueField: page
    required: false
  - name: position
    label: Position on global photo gallery page (not the gallery above)
    widget: number
    valueType: int
  meta:
  - name: date
    label: Created at
    widget: date
    format: YYYY-MM-DD HH:mm:ss ZZ

- label: Site Settings
  name: settings
  description: Content of special pages like titles, button labels etc.
  files:
    - name: authors
      label: "\U0001F6AB Authors (edit only on GitHub)"
      label_singular: Author
      file: _data/authors.yml
      fields: []

    - name: header
      label: Global header
      file: _data/header.yml
      fields:
        - name: logo
          label: Logo
          widget: image
        - name: claim
          label: Claim
          widget: string
        - name: search
          label: Search field placeholder
          widget: string
