backend:
  name: git-gateway
  branch: master

media_folder: uploads

collections:
- name: galleries
  label: Galleries
  label_singular: Gallery
  description: >-
    Photo galleries linked to any content via its address. Gallery
    photos are displayed under the content.
  folder: _galleries
  create: true
  fields:
  - name: page
    label: Page address (copy and paste from web browser address bar, and remove https:// and domain)
    widget: string
  - name: position
    label: Position
    widget: number
    valueType: int
  meta:
  - name: date
    label: Created at
    widget: date
    format: YYYY-MM-DD HH:mm:ss ZZ

- name: posts
  label: News
  folder: _posts
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  create: true
  fields:
  - name: title
    label: Title
    widget: string
  - name: image
    label: Image
    widget: image
  - name: body
    label: Content
    widget: markdown
  - name: published
    label: Published
    widget: boolean
  - name: date
    label: Published at
    widget: date
    format: YYYY-MM-DD

- name: showcases
  label: Showcases
  label_singular: Showcase
  description: Big photos that are displayed on the homepage.
  folder: _showcases
  create: true
  fields:
  - name: title
    label: Title
    widget: string
  - name: image
    label: Image
    widget: image
  - name: position
    label: Position
    widget: number
    valueType: int
  meta:
  - name: date
    label: Created at
    widget: date
    format: YYYY-MM-DD HH:mm:ss ZZ

- name: filterable_tags
  label: Categories
  label_singular: Category
  description: >-
    Categorization and filtering of photos. Arbitrary categories can
    be added to photos (i.e., photo categories don’t have to defined
    here). But if you want a category to appear as a filter option on
    the global photo gallery page, you have to define it here with
    exactly same name as you use in photos.
  folder: _filterable_tags
  create: true
  fields:
  - name: name
    label: Name
    widget: string
  - name: position
    label: Position
    widget: number
    valueType: int
  meta:
  - name: date
    label: Created at
    widget: date
    format: YYYY-MM-DD HH:mm:ss ZZ

- name: photos
  label: Photos
  label_singular: Photo
  description: >-
    Photos in linked to galleries. All photos are displayed on global
    photo gallery.
  folder: _photos
  create: true
  fields:
  - name: title
    label: Title
    widget: string
  - name: image
    label: Image
    widget: image
  - name: body
    label: Description
    widget: markdown
    required: false
  - name: author
    label: Author
    widget: string
    required: false
  - name: tags
    label: Categories
    widget: list
    required: false
  - name: gallery
    label: Gallery
    widget: relation
    collection: galleries
    searchFields:
    - page
    valueField: page
    required: false
  - name: position
    label: Position on global photo gallery page (not the gallery above)
    widget: number
    valueType: int
  meta:
  - name: date
    label: Created at
    widget: date
    format: YYYY-MM-DD HH:mm:ss ZZ
